# See https://doc.rust-lang.org/cargo/reference/manifest.html
[package]
name = "clinvoice-adapter-postgres"
version = "0.7.1"
authors = ["Iron-E <code.iron.e@gmail.com>"]
description = "Postgres filesystem support for `clinvoice-adapter` 0.8"

edition = "2021"
license = "GPL3"
readme = "README.md"
repository = "https://www.github.com/Iron-E/clinvoice-adapter-postgres"

[dependencies]
clinvoice-adapter = {branch="release/0.17", default-features = false, git = "https://github.com/Iron-E/clinvoice-adapter"}
clinvoice-finance = {branch = "release/0.4", git = "https://github.com/Iron-E/clinvoice-finance"}
clinvoice-match = {branch = "release/0.6", git = "https://github.com/Iron-E/clinvoice-match"}
clinvoice-schema = {branch = "release/0.9", git = "https://github.com/Iron-E/clinvoice-schema"}

async-trait = "0.1"
futures = "0.3"
humantime = "2"
shellexpand = "2"
sqlx = {features = ["chrono", "decimal", "macros", "postgres", "runtime-tokio-rustls", "tls"], version = "0.5"}
thiserror = "1"

[dev-dependencies]
dotenv = "0.15.0"
lazy_static = "1"
pretty_assertions = "1"
tokio = {features = ["macros", "rt-multi-thread"], version = "1"}

[features]
default = []
