--- @param date_close integer|nil
--- @param date_open integer|nil
--- @param invoice_date_issued integer|nil
--- @param invoice_date_paid integer|nil
local function check(date_open, date_close, invoice_date_issued, invoice_date_paid, expected)
	local job_is_open_before_closed = date_close == nil or date_close > date_open
	local job_is_closed_before_invoice_issued = invoice_date_issued == nil or (date_close ~= nil and invoice_date_issued > date_close)
	local invoice_is_issued_before_paid = invoice_date_paid == nil or (invoice_date_issued ~= nil and invoice_date_paid > invoice_date_issued)

	assert(
		(job_is_open_before_closed and job_is_closed_before_invoice_issued and invoice_is_issued_before_paid) == expected,
		"\n\tjob is open before closed: " .. tostring(job_is_open_before_closed) ..
		"\n\tinvoice is issued before paid: " .. tostring(invoice_is_issued_before_paid) ..
		"\n\tjob is closed before invoice issued: " .. tostring(job_is_closed_before_invoice_issued) ..
		"\n\texpected: " .. tostring(expected)
	)
end

check(1, 2, 3, 4, true)
check(1, 2, 3, nil, true)
check(1, 2, 4, 3, false)
check(1, 2, 4, nil, true)
check(1, 2, nil, 3, false)
check(1, 2, nil, 4, false)
check(1, 2, nil, nil, true)
check(1, 3, 2, 4, false)
check(1, 3, 2, nil, false)
check(1, 3, 4, 2, false)
check(1, 3, 4, nil, true)
check(1, 3, nil, 2, false)
check(1, 3, nil, 4, false)
check(1, 3, nil, nil, true)
check(1, 4, 2, 3, false)
check(1, 4, 2, nil, false)
check(1, 4, 3, 2, false)
check(1, 4, 3, nil, false)
check(1, 4, nil, 2, false)
check(1, 4, nil, 3, false)
check(1, 4, nil, nil, true)
check(1, nil, 2, 3, false)
check(1, nil, 2, 4, false)
check(1, nil, 2, nil, false)
check(1, nil, 3, 2, false)
check(1, nil, 3, 4, false)
check(1, nil, 3, nil, false)
check(1, nil, 4, 2, false)
check(1, nil, 4, 3, false)
check(1, nil, 4, nil, false)
check(1, nil, nil, 2, false)
check(1, nil, nil, 3, false)
check(1, nil, nil, 4, false)
check(1, nil, nil, nil, true)
check(2, 1, 3, 4, false)
check(2, 1, 3, nil, false)
check(2, 1, 4, 3, false)
check(2, 1, 4, nil, false)
check(2, 1, nil, 3, false)
check(2, 1, nil, 4, false)
check(2, 1, nil, nil, false)
check(2, 3, 1, 4, false)
check(2, 3, 1, nil, false)
check(2, 3, 4, 1, false)
check(2, 3, 4, nil, true)
check(2, 3, nil, 1, false)
check(2, 3, nil, 4, false)
check(2, 3, nil, nil, true)
check(2, 4, 1, 3, false)
check(2, 4, 1, nil, false)
check(2, 4, 3, 1, false)
check(2, 4, 3, nil, false)
check(2, 4, nil, 1, false)
check(2, 4, nil, 3, false)
check(2, 4, nil, nil, true)
check(2, nil, 1, 3, false)
check(2, nil, 1, 4, false)
check(2, nil, 1, nil, false)
check(2, nil, 3, 1, false)
check(2, nil, 3, 4, false)
check(2, nil, 3, nil, false)
check(2, nil, 4, 1, false)
check(2, nil, 4, 3, false)
check(2, nil, 4, nil, false)
check(2, nil, nil, 1, false)
check(2, nil, nil, 3, false)
check(2, nil, nil, 4, false)
check(3, 1, 2, 4, false)
check(3, 1, 2, nil, false)
check(3, 1, 4, 2, false)
check(3, 1, 4, nil, false)
check(3, 1, nil, 2, false)
check(3, 1, nil, 4, false)
check(3, 1, nil, nil, false)
check(3, 2, 1, 4, false)
check(3, 2, 1, nil, false)
check(3, 2, 4, 1, false)
check(3, 2, 4, nil, false)
check(3, 2, nil, 1, false)
check(3, 2, nil, 4, false)
check(3, 2, nil, nil, false)
check(3, 4, 1, 2, false)
check(3, 4, 1, nil, false)
check(3, 4, 2, 1, false)
check(3, 4, 2, nil, false)
check(3, 4, nil, 1, false)
check(3, 4, nil, 2, false)
check(3, 4, nil, nil, true)
check(3, nil, 1, 2, false)
check(3, nil, 1, 4, false)
check(3, nil, 1, nil, false)
check(3, nil, 2, 1, false)
check(3, nil, 2, 4, false)
check(3, nil, 2, nil, false)
check(3, nil, 4, 1, false)
check(3, nil, 4, 2, false)
check(3, nil, 4, nil, false)
check(3, nil, nil, 1, false)
check(3, nil, nil, 2, false)
check(3, nil, nil, 4, false)
check(3, nil, nil, nil, true)
check(4, 1, 2, 3, false)
check(4, 1, 2, nil, false)
check(4, 1, 3, 2, false)
check(4, 1, 3, nil, false)
check(4, 1, nil, 2, false)
check(4, 1, nil, 3, false)
check(4, 1, nil, nil, false)
check(4, 2, 1, 3, false)
check(4, 2, 1, nil, false)
check(4, 2, 3, 1, false)
check(4, 2, 3, nil, false)
check(4, 2, nil, 1, false)
check(4, 2, nil, 3, false)
check(4, 2, nil, nil, false)
check(4, 3, 1, 2, false)
check(4, 3, 1, nil, false)
check(4, 3, 2, 1, false)
check(4, 3, 2, nil, false)
check(4, 3, nil, 1, false)
check(4, 3, nil, 2, false)
check(4, 3, nil, nil, false)
check(4, nil, 1, 2, false)
check(4, nil, 1, 3, false)
check(4, nil, 1, nil, false)
check(4, nil, 2, 1, false)
check(4, nil, 2, 3, false)
check(4, nil, 2, nil, false)
check(4, nil, 3, 1, false)
check(4, nil, 3, 2, false)
check(4, nil, 3, nil, false)
check(4, nil, nil, 1, false)
check(4, nil, nil, 2, false)
check(4, nil, nil, 3, false)
check(4, nil, nil, nil, true)
